apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: kafka-manager
  name: kafka-manager
spec:
  selector:
    k8s-app: kafka-manager
  ports:
  - port: 80
    targetPort: 9000
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: kafka-manager
  name: kafka-manager
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: kafka-manager
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: kafka-manager
      name: kafka-manager
    spec:
      containers:
      - env:
        - name: TZ
          value: Asia/Shanghai
        - name: ZK_HOSTS
          value: "192.168.1.104:2181" 
        image: registry.cn-hangzhou.aliyuncs.com/daianla/kafka-manager:1.3.3.14
        imagePullPolicy: IfNotPresent
        name: kafka-manager
        securityContext:
          privileged: false
          procMount: Default
      imagePullSecrets:
      - name: kube-registry