apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
kubernetesVersion: v1.14.1
imageRepository: registry.cn-hangzhou.aliyuncs.com/google_containers

controlPlaneEndpoint: 192.168.1.100

apiServer:
  timeoutForControlPlane: 3m0s
  CertSANs:
  - 192.168.1.100
  - 127.0.0.1

etcd:
  local:
    extraArgs:
      advertise-client-urls: https://192.168.1.104:2379
      initial-advertise-peer-urls: https://192.168.1.104:2380
      #initial-cluster-state: existing
      initial-cluster: node3=https://192.168.1.104:2380
      listen-client-urls: https://127.0.0.1:2379,https://192.168.1.104:2379
      listen-peer-urls: https://192.168.1.104:2380
    peerCertSANs:
    - 192.168.1.104
    serverCertSANs:
    - 192.168.1.104

networking:
  podSubnet: 10.244.0.0/16

---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: "ipvs"