kind: Pod
apiVersion: v1
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
  labels:
    component: keepalived
    tier: control-plane
  name: kube-keepalived
  namespace: kube-system
spec:
  hostNetwork: true
  priorityClassName: system-cluster-critical
  containers:
  - name: kube-keepalived
    image: osixia/keepalived:1.4.4
    env:
    - name: KEEPALIVED_VIRTUAL_IPS
      value: "#PYTHON2BASH:['192.168.6.103']"
    - name: KEEPALIVED_INTERFACE
      # 此值为网络设备名称，使用ifconfig命令查看
      value: em1
    - name: KEEPALIVED_UNICAST_PEERS
      value: "#PYTHON2BASH:['192.168.6.100','192.168.6.101','192.168.6.102']"
    - name: KEEPALIVED_PASSWORD
      value: hello
    resources:
      requests:
        cpu: 500m
    securityContext:
      privileged: true
      capabilities:
        add:
        - NET_ADMIN
